### NumPy

NumPy is a fundamental library for scientific computing in Python.    
It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.   


In [2]:
import numpy as np #np is an alias for numpy

In [6]:
## Create arrays using numpy

# Creating a 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) #1 row, 5 columns
# Reshaping into 1,4 won't work because there are 5 elements
# No. of square braces (considering either opening or closing) is equal to the number of dimensions

array([[1, 2, 3, 4, 5]])

In [8]:
arr2 = np.array([[1,2,3,4,5]]) #Using nested list
print(arr2.shape)

(1, 5)


In [ ]:
# 2D array
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [13]:
arr3 = np.arange(0,10,2)
print(arr3)
arr3 = arr3.reshape(5,1)
print(arr3)

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]


In [14]:
arr4 = np.ones((3,4))
print(arr4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
## Identity matrix or array
## All the principal diagonal elements are 1, rest all are 0
arr5 = np.eye(3)
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
## Attributes of NumPy array

arr = np.array([[1,2,3],[4,5,6]])
print("Array:\n", arr) # Array
print("Shape: ", arr.shape)
print("Number of dimensions: ", arr.ndim)
print("Size (number of elements): ", arr.size)
print("Datatype: ", arr.dtype) #may vary depending on platform
print("Item size (in bytes): ", arr.itemsize) #may vary based on platform

Array:
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size (number of elements):  6
Datatype:  int64
Item size (in bytes):  8


In [ ]:
## Numpy vectorized operations
## Return type will be array
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise addittion
print("Adittion: ", arr1+arr2)

## Element wise subtraction
print("Subtraction: ", arr2-arr1)

## Element wise multiplication
print("Multiplication: ", arr1*arr2)

## Element wise division
print("Division: ", arr2/arr1)

Addittion:  [11 22 33 44 55]
Subtraction:  [ 9 18 27 36 45]
Multiplication:  [ 10  40  90 160 250]
Division:  [10. 10. 10. 10. 10.]


In [31]:
## Universal functions
## Applies to the entire array
arr = np.array([1,2,3,4,5])

## square root
print(np.sqrt(arr))

## exponential
print(np.exp(arr))

## sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [44]:
## Array slicing and indexing
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

## Accessing any element = arr[row][column]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr[0] #Gets the first row

array([1, 2, 3])

In [34]:
arr[0][0] #Gets the first element in the first row

np.int64(1)

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
## Displaying 5,6,8,9 only
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [39]:
## Displaying 2,3,5,6
arr[0:2,1:]

array([[2, 3],
       [5, 6]])

In [40]:
## Displaying 2,5,8
arr[0:,1]

array([2, 5, 8])

In [42]:
## Modify array elements
print(arr)
arr[0,0] = 100
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [45]:
## Modifying multiple array elements
print(arr)
arr[0,0:] = 100
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[100 100 100]
 [  4   5   6]
 [  7   8   9]]


In [46]:
## Practical application
## Statistical concept -- Normalization
## To change the data such that it has a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

## Calculating the mean and standard deviatio
mean = np.mean(data)
std_dev = np.std(data)

## Normalizing the data
normalized_data = (data-mean) / std_dev
print("Normalized data: ", normalized_data)


Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [47]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

## Mean
mean = np.mean(data)
print("Mean: ", mean)

## Median
median = np.median(data)
print("Median: ", median)

## Standard Deviation
std_dev = np.std(data)
print("Standard deviation: ", std_dev)

## Variance
variance = np.var(data)
print("Variance: ", variance)

Mean:  5.5
Median:  5.5
Standard deviation:  2.8722813232690143
Variance:  8.25


In [48]:
## Logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
data > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [49]:
## Retrieving all the elements that are greater than 5
data[data>5]

array([ 6,  7,  8,  9, 10])

In [52]:
## Retrieving all the elements taht are greater than 5 but less than or equal to 9
data[(data > 5) & (data <= 9)]

array([6, 7, 8, 9])

In [53]:
## Retrieving all the values that are outside the range 5 to 8
data[(data<5) | (data > 8)]

array([ 1,  2,  3,  4,  9, 10])